# -- ignored / annoying rules --

- ignore: {name: "Use fewer imports"}
- ignore: {name: "Use if"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Reduce duplication"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Use head"}
- ignore: {name: "Use unwords"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use elem"}
- ignore: {name: "Use infix"}
- ignore: {name: "Use section"}
- ignore: {name: "Move brackets to avoid $"}
- ignore: {name: "Use zipWith"}
- ignore: {name: "Redundant flip"}
- ignore: {name: "Redundant $!"}
- ignore: {name: "Redundant <$>"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Use underscore"}
- ignore: {name: "Functor law"}
- ignore: {name: "Use record patterns"}

# -- custom rules --

# we should use witch
- functions:
  - {name: fromIntegralSized, within: [], message: "use into, tryInto, truncateTo, or (un)signedWord"}
  - {name: fromIntegral, within: [], message: "use into, tryInto, truncateTo, or (un)signedWord"}
  - {name: fromInteger, within: [], message: "use into, tryinto, truncateto, or (un)signedword"}
  - {name: toIntegralSized, within: [], message: "use into, tryinto, truncateto, or (un)signedword"}
  - {name: toIntegral, within: [], message: "use into, tryinto, truncateto, or (un)signedword"}
  - {name: toInteger, within: [], message: "use into, tryinto, truncateto, or (un)signedword"}

# we should use internalError
- error: {lhs: error, rhs: internalError, name: "use internalError"}

# we should use pure
- error: {lhs: return, rhs: pure}
